name: Licensed

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Check licenses
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # prefer to use a full fetch for licensed workflows
      # https://github.com/jonabc/setup-licensed/releases/tag/v1.1.1
      - uses: jonabc/setup-licensed@v1
        with:
          version: '3.x'
      - uses: ./.github/actions/install-dependencies
      - run: licensed cache
      - run: licensed status
